project:
  type: website

website:
  title: "ECE 3704 Notes"
  navbar:
    left:
      - href: index.qmd
        text: Table of Contents
      - text: "Lectures"
        menu:
          - lecture2.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



