---
format:
  html:
    toc: true
  pdf: default
  docx: default
  odt: default
  epub: default
  
title: "2. Modeling and Characterization of Signals and Systems"

author:
  - name: Chris Wyatt
  - email: clwyatt@vt.edu
  - affiliations:
    - Bradley Department of Electrical and Computer Engineering, Virginia Tech

date: last-modified

abstract: |
   Today's lecture is a review of material from ECE 2714. We will review the modeling and characterization of continuous-time and discrete-time signals and systems.
---

# Signals

Signals are modeled as functions $f: A \rightarrow B$ where $A$ and $B$ are sets.

Examples of some commonly encountered signals:

*  $A\in \mathbb{R}$, $B\in \mathbb{R}$: CT (Analog) signals
*  $A\in \mathbb{Z}$, $B\in \mathbb{R}$: DT real-valued signals
*  $A\in \mathbb{Z}$, $B\in \mathbb{C}$: DT complex-valued signals
*  $A\in \mathbb{R}$, $B\in \mathbb{R}^2$: two-channel CT (Analog Stereo) signals

To model signals we can build them up from primitive signals using transformations and combinations.

Some examples of primitive CT signals:

*  $\delta(t)$, the delta function
*  $u(t)$, the step function
*  $e^{st}\; s\in\mathbb{C}$, the complex exponential

Recall the important relations for the complex exponential. Let $s = \alpha + j\beta$, where $\alpha, \beta \in \mathbb{R}$, then

$$
  e^{st} = e^{(\alpha + j\beta)t} = e^{\alpha t}\, e^{j\beta t} = e^{\alpha t}\left(\cos(\beta t) + j\sin(\beta t) \right)
$$

By combining primitive signals we can create other signals. For example, the cosine function can be written as the weighted, linear combination of two complex exponentials

$$
  \cos(\omega t) = \frac{1}{2} e^{j\omega_0 t} + \frac{1}{2} e^{-j\omega_0 t}
$$

A similar example is the Fourier Series representation of periodic CT signals, $x(t)$, that meet the Direchlet conditions. It is an infinite weighted, linear combination of complex exponentials

$$
  x(t) = \sum\limits_{k = -\infty}^{\infty} a_k\, e^{jk\omega_0\, t}
$$

We can also think about decomposing complex signals into primitive functions rather than building them up. Recall the CT Fourier decomposition (transform) of a signal $x(t)$ is given by the improper, definite integral:

$$
  X(\omega) = \int\limits_{-\infty}^{\infty} x(t) e^{j\omega\, t}\; dt
$$

which applies to many, but not all, signals.

Some example primitives for DT signals are:

* $\delta[n]$, the discrete delta function
* $u[n]$, the discrete unit step
* $z^n,\; z\in\mathbb{C}$, the complex exponential

Recall the DT complex exponential can be written as follows. Let $z = r\, e^{j\theta}, \, r,\theta\in\mathbb{R}$, then

$$
  z^n = \left( r\, e^{j\theta} \right)^n = r^n\, e^{j\theta\, n} = r^n\left(\cos(\theta\, n) + j\sin(\theta\, n) \right)
$$

Note: the type of signal, DT or CT, real-valued or complex valued, etc. can usually be inferred. To make this easier we use square brackets $[]$ to define DT signals and parenthesis $()$ to define CT signals.

As before, we can construct more complex DT signals by taking products and weighted linear combinations of these primitive signals, for example:

* $\left(\gamma\right)^n\; u[n],\; \gamma\in\mathbb{R}$
* $\left(\gamma\right)^n\,\cos(\omega_0 n)\; u[n],\; \gamma,\omega_0\in\mathbb{R}$

In many cases the same signals can be expressed in different forms. In the last example above

$$
  \left(\gamma\right)^n\,\cos(\omega_0 n)\; u[n] = \left(z\right)^n + \left(z^*\right)^n
$$

where $z = \frac{\gamma}{2}\, e^{j\theta}$.

The corresponding Fourier decomposition for a DT signal $x[n]$ is

$$
  X(\omega) = \sum\limits_{-\infty}^{\infty} x[n] e^{j\omega\, n}
$$

a periodic function in $2\pi$, which may or may not exist for any given signal of interest.


